# Generated by Django 3.1.2 on 2020-10-15 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='descripttion',
            new_name='desc',
        ),
    ]
